### ISSUE TITLE
Slow and incomplete loading of the Geology Layers

### ISSUE THREAD

**Issue by Stefankirby** [UGS-GIO/forgeApp#8]
Can we improve the loading speed of the geology layers?

**Comment by marthajensen** [comment]
I added some more resources to this Service in ArcGIS Server.  Hopefully it will load a bit faster.  We might need to look at the queries on this layer and possibly index the fields that are being queried.

**Comment by marshallrobinson** [comment]
@marthajensen, @Stefankirby, have you seen any improvement to speed after Martha added more server resources?

**Comment by marthajensen** [comment]
@Stefankirby check to see if the Geologic layers are loading faster -- I am seeing improvement.
 I did the following (these notes are for my record)
-Instead of allowing an automatic projection of the data, I reprojected it to WGS84
- Cached the map service on the Server for Levels 11-16 (Metropolitan Area to Streets). This resulted in a very small cache of 20 mb
-Created a Shared Pool instead of a Dedicated Instance on the Server
